const ACTIONSTYPES = {
    FETCH_BOOK_REQUEST: 'FETCH_BOOK_REQUEST',
    FETCH_BOOK_SUCCESS: 'FETCH_BOOK_SUCCESS',
    FETCH_BOOK_FAILURE: 'FETCH_BOOK_FAILURE',
    BOOK_ADDED_TO_CART: 'BOOK_ADDED_TO_CART',
    BOOK_MINUS_TO_CART: 'BOOK_MINUS_TO_CART',
    BOOK_DELETE_TO_CART: "BOOK_DELETE_TO_CART"
}

export default ACTIONSTYPES;
